### PR TITLE
first pass of theme update

### PR DESCRIPTION
**Pull request by mmacke01**

### CODE REVIEW

**Comment by ipavl** [comment]
There's still kind of a red tint on the main screen when the side menu is open or the app is transitioning between screens.

The system status bar (above the menu bar) on Android is black and turns to grey after authenticating with FitBit - I'm not sure why it changes. It is often a darker shade of the menu bar for a lot of apps. I'm not sure if we care about that for the moment.

**Comment by Andrewwelton** [comment]
For a "first pass" I think it is ok, but it is definitely going to need more work around cases like what Ian mentioned.

👍

**Comment by ipavl** [comment]
Yeah, it's fine for now. Neither are huge.

**Comment by mmacke01** [comment]
Thanks for listing some of the issues, I'll make a ticket in Trello to track those when we do a more complete style change. I know this isn't perfect - just wanted to get an early version in so my eyes stop burning.

**Pull request merged**
