### PR TITLE
Cat distance

### PR DESCRIPTION
**Pull request by Andrewwelton**
We now have graphs for distance and they're super pretty. So yeah

### CODE REVIEW

**Review by mmacke01 — COMMENTED** [review]
:+1

**Comment by ipavl** [comment]
Looks fine as long as you have authenticated with FitBit before trying to view data, otherwise it'll show no week data initially and error when you switch weeks.

**Comment by Andrewwelton** [comment]
If we're ok with that for now Ian, we can file it as an issue and resolve it in the next pass?

I was thinking about that earlier, we should probably find a way to ensure we have FitBit access before doin stuff

**Comment by ipavl** [comment]
I think that's fine. It's from not having any credentials in AsyncStorage as opposed to anything in these changes.

**Pull request merged**
